openapi: 3.0.1
info:
  title: File Orchestrator
  description: All endpoints
  license:
    name: GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0
  version: v1
servers:
  - url: http://localhost:8080
    description: DEV
  - url: http://update-me.somewhere.com:8080
    description: PROD
paths:
  /api/v1/short-selling-eligible-securities:
    post:
      tags:
        - file-upload
      description: Start a upload process for Short Selling Eligible Securities
      operationId: uploadShortSellingEligibleSecurities
      responses:
        '201':
          description: Created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ProcessResponse'
  /api/v1/uk-list-exempted-shares:
    post:
      tags:
        - file-upload
      description: Start a upload process for UK List Exempted Shares
      operationId: uploadUkListExemptedShares
      responses:
        '201':
          description: Created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ProcessResponse'
  /api/v1/processes:
    get:
      tags:
        - process
      description: List all process
      operationId: listProcesses
      responses:
        '200':
          description: Ok
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessResponse'
  /api/v1/securities:
    get:
      tags:
        - security
      description: List all securities
      operationId: listSecurities
      responses:
        '200':
          description: Ok
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SecurityResponse'
  /api/v1/currencies:
    get:
      tags:
        - currency
      description: List all currencies
      operationId: listCurrencies
      responses:
        '200':
          description: Ok
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurrencyResponse'
components:
  schemas:
    ProcessResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fileName:
          type: string
        startedAt:
          type: string
        finishedAt:
          type: string
    SecurityResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
    CurrencyResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
