--liquibase formatted sql
--changeset hezzine:create-SHORT_SELLING_ELIGIBLE_SECURITY-table splitStatements:true endDelimiter:;

CREATE TABLE SHORT_SELLING_ELIGIBLE_SECURITY (

  ID  INTEGER PRIMARY KEY,
  ROW_NUMBER INTEGER,
  STOCK_CODE VARCHAR(255) NOT NULL,
  STOCK_SHORT_NAME VARCHAR(255),
  CURRENCY_CODE VARCHAR(255) NOT NULL,
  SECURITY_TYPE VARCHAR(255),
  EXEMPT_FROM_TICK_RULE VARCHAR(255),
  REMARKS VARCHAR (255),
  PROCESS_ID INTEGER NOT NULL,
  CONSTRAINT FK_PROCESS_ID FOREIGN KEY (PROCESS_ID) REFERENCES PROCESS (ID)
  
);

