--liquibase formatted sql
--changeset hezzine:create-ISSUER-table splitStatements:true endDelimiter:;
CREATE TABLE ISSUER
(
   ISIN VARCHAR (255) PRIMARY KEY,
   NAME VARCHAR (255) NOT NULL,
   DATE_ADDED DATE
);
--changeset hezzine:create-UK_LIST_OF_EXEMPTED_SHARES-table splitStatements:true endDelimiter:;
CREATE TABLE UK_LIST_OF_EXEMPTED_SHARES
(
   ID Bigint PRIMARY KEY auto_increment,
   ROOT VARCHAR (255),
   ISIN VARCHAR (255) ,
   COUNTR_YCODE VARCHAR (255) ,
   RELEVANT_AUTHORITY VARCHAR (255) ,
   MODIFICATION_DATE_STR DATE,
   VERSION Bigint NOT NULL,
   NAME VARCHAR (255),
   STATUS VARCHAR (255),
   TIME_STAMP DATE,
   PROCESS_ID Bigint  ,
   EXEMPTION_START_DATE_STR DATE,
   CONSTRAINT FK_ISSUER_ISIN FOREIGN KEY (ISIN) REFERENCES ISSUER (ISIN),
   CONSTRAINT FK_PROCESS_ID_UK FOREIGN KEY (PROCESS_ID) REFERENCES PROCESS (ID)
);